### ISSUE TITLE
Error compiling the new firmware

### ISSUE THREAD

**Issue by leon-uhs** [luispl77/433Screen-SignalHacker#4]
exit status 1
'class RFM69LPL' has no member named 'updateSettings'; did you mean 'readAllSettings'?

![微信图片_20230604103842](https://github.com/luispl77/433Screen-SignalHacker/assets/25344138/9d73473f-d18c-4acc-9b94-5f6204bedce3)

**Comment by luispl77** [comment]
Hello, it seems you have an old version of the RFM69LPL library. Please download the [most recent version](https://github.com/luispl77/RFM69LPL), as it has changes made yesterday to accommodate the EEPROM feature. Thank you

**Comment by leon-uhs** [comment]
ok，Do you have email or other instant chat software?

**Comment by luispl77** [comment]
Yes, you can add me on discord, luispl#9021

**Comment by luispl77** [comment]
I also fixed a bug right now with the EEPROM first write in the commit [19436fe](https://github.com/luispl77/433Screen-SignalHacker/commit/19436fee8bd8ca27aefb85ef4367171888b6b933)
